name: Docker website CI

on:
  push: 
    branches: ['api-implementation']
    paths:
      - 'src/**'

jobs:
  deploy:
    name: Docker build and deploy to Azure Container Instances
    runs-on: ubuntu-latest

    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build website image
        run: |
          docker build -t hugocerrillo/notificaciones:latest -f Dockerfile .

      - name: Publish website image
        run: |
          docker push hugocerrillo/notificaciones:latest
      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          resource-group: topicos-notificaciones
          dns-name-label: notificacionesapi-${{ github.run_id }}
          image: hugocerrillo/notificaciones:latest
          registry-login-server: docker.io
          registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          name: notificaciones-api
          location: 'East US'
          ports: '3000'
          restart-policy: OnFailure
